version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000:80
    ports:
      - "5000:80"

  client:
    ports:
      - "5001:3000"

  proxy:
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"